"""add RECORDED to SourceType enum

Revision ID: 39d8e0e0ae8d
Revises: c63188f32bc3
Create Date: 2025-09-26 22:18:26.110653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d8e0e0ae8d'
down_revision: Union[str, None] = 'c63188f32bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE source_type ADD VALUE IF NOT EXISTS 'recorded';")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
