"""Added media_input Model

Revision ID: a13a168f2738
Revises: 
Create Date: 2025-07-18 16:39:25.703515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13a168f2738'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('UPLOAD', 'URL', name='source_type'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('source_location', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('diarization_csv_path', sa.String(), nullable=True),
    sa.Column('summary_json_path', sa.String(), nullable=True),
    sa.Column('audio_summary_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_inputs')
    # ### end Alembic commands ###
