version: '3.8'

services:
  db:
    image: postgres:14.19
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    workking_dir: /app
    depends_on:
      - db
    env_file: